### ISSUE TITLE
Substitutes

### ISSUE THREAD

**Issue by travankor** [flatwhatson/guix-channel#1]
Nice channel! I was looking for emacs native-comp+pgtk and found this.

I'm wondering if you build this regularily, do you [publish](https://guix.gnu.org/manual/en/html_node/Invoking-guix-publish.html) substitutes for this channel? Nix has [cachix](https://cachix.org/) for this purpose, but I don't know if Guix has anything similar.

**Comment by flatwhatson** [comment]
Sorry, I don't currently host a substitute server for these packages.

I'm not aware of a community substitute server like cachix for guix, but it would be awesome if such a thing were to exist!

There will be a discussion in the upcoming [Guix Day Conference](https://guix.gnu.org/en/blog/2020/online-guix-day-announce-2/) about hosting substitutes on IPFS which might be another option in the future.

**Comment by travankor** [comment]
Compiling libgccjit-10 causes an OOM for me, so I switched to 9 (which has substitutes) for now. Also I turned `NATIVE_FULL_AOT` off to save some compilation time.

I really hope the proposed P2P substitute model works out!
