### ISSUE TITLE
Error installing emacs-native-comp: "emacs-next-pgtk: unbound variable"

### ISSUE THREAD

**Issue by vindarel** [flatwhatson/guix-channel#11]
Hi,

I tried to install Emacs like said in the README:

```
git clone https://github.com/flatwhatson/guix-channel.git
guix install -L ./guix-channel emacs-native-comp
```

I get:

```
error: emacs-next-pgtk: unbound variable
hint: Did you forget a `use-modules' form?

guix install: error: emacs-native-comp: unknown package
```

Anything I can do?

Best,

and thanks for this channel.

    guix (GNU Guix) 1.2.0

**Comment by flatwhatson** [comment]
Your guix is out of date, you need to `guix pull`.

**Comment by vindarel** [comment]
I stopped the compilation when my home got less than 100MB of free space (from ±3GB), but it was working. Thanks.
