### ISSUE TITLE
Unable to build libgccjit - Void Linux

### ISSUE THREAD

**Issue by e-eight** [flatwhatson/guix-channel#13]
I am using guix on void linux, and trying to build `libgccjit-10`, but it is failing. Here is the
[build log](https://github.com/flatwhatson/guix-channel/files/6567159/5h1dvy0b00i7j8z8bv5907lc61wfdl-libgccjit-10.3.0.drv.gz).

**Comment by duckwork** [comment]
I've duplicated this issue on Debian 11; as far as I can tell the same issue occurs.  Build log is here:
[wfc424p88si9zwsck5r0mql6gaxzdr-libgccjit-10.3.0.drv.gz](https://github.com/flatwhatson/guix-channel/files/7036313/wfc424p88si9zwsck5r0mql6gaxzdr-libgccjit-10.3.0.drv.gz)

EDIT: toward the end of the file, what you mention is confirmed: I ran out of space on my device.  Thanks @flatwhatson !

**Comment by 2ndemosthenes** [comment]
I'm having the same kind of issue on Opensuse, Guix was building libgccjit for over an hour and then failed.
Here is my [build log](https://github.com/flatwhatson/guix-channel/files/7049798/5h1dvy0b00i7j8z8bv5907lc61wfdl-libgccjit-10.3.0.drv.gz), but there's nothing helpful there. Maybe trying with gcc11 would help? I'm not familiar with Guix, but on [OBS](https://build.opensuse.org/package/show/home:agraul/emacs-pgtk-nativecomp) someone has built it with gcc11, so it's possible.

**Comment by duckwork** [comment]
It's possible (I've not tested it myself, but someone on IRC had this issue and solved it) that you don't have enough RAM.  Guix builds in /tmp by default (I think), which on some Linuxes is in tmpfs on RAM.  As building takes up more and more memory, the build process slows and slows (because there's less memory) until it runs out.  Whoever I spoke to (sorry I've forgotten who it was) said if you set `TMPDIR` to something *not* on tmpfs, it should work. I.e.,

    $ TMPDIR=/var/tmp guix install <package>

As I've said, I've not tested this myself but it's highly likely that's the problem *I* was running into.

**Comment by 2ndemosthenes** [comment]
> It's possible (I've not tested it myself, but someone on IRC had this issue and solved it) that you don't have enough RAM. Guix builds in /tmp by default (I think), which on some Linuxes is in tmpfs on RAM. As building takes up more and more memory, the build process slows and slows (because there's less memory) until it runs out. Whoever I spoke to (sorry I've forgott ben who it was) said if you set `TMPDIR` to something _not_ on tmpfs, it should work. I.e.,
> 
> ```
> $ TMPDIR=/var/tmp guix install <package>
> ```
> 
> As I've said, I've not tested this myself but it's highly likely that's the problem _I_ was running into.

Thank you! I tried it and it worked (after compiling for TWO hours), the command you have provided didn't work though, I added ` 'TMPDIR=/gnu/tmp' ` to Environment variable in the guix-daemon systemd service.

**Comment by 2ndemosthenes** [comment]
@flatwhatson Has there been any progress with [this](https://issues.guix.gnu.org/44775)?

**Comment by flatwhatson** [comment]
These build failures were all related to running out of memory, usually due to having /tmp on a ramdisk.  Guix builds in the /tmp directory and the libgccjit build (which is basically a gcc build) takes a lot of space.  Please open a new ticket if you're encountering build problems.
