### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by alphapapa** [flatwhatson/guix-channel#14]
Hi @flatwhatson,

I just wanted to thank you for putting this together.  I wasn't able to use a new-enough version of GCC to get libgccjit on my current distro, but I'm able to use Guix inside of it to get newer versions of some software.  I followed the directions, added your channel, and after about an hour, I had an `emacs-28.0.50` binary that includes the native-comp features, as well as some recent additions to Emacs 28 that I was wanting to use.  (I had been using Andrea Corallo's Docker image to run Emacs 28, which works well, but isn't always updated.)

It works great with my `with-emacs.sh` script: https://github.com/alphapapa/with-emacs.sh  I just run `with-emacs -e emacs-28.0.50 -d ~/src/emacs/configs/ap.el` and I get Emacs 28.0.50 with native-comp running my dedicated Emacs 28 config.

I tried, a long time ago, to make libgccjit and Emacs native-comp packages for Guix, but I know very little about Guix, and it was more than I could learn in a reasonable amount of time.  So I'm very thankful that you did this and published it for others to use.  :)

**Comment by daviwil** [comment]
I second that!  I use Emacs 28 built from this package definition every day.

**Comment by timmydo** [comment]
+1. Thanks for your native-comp pgtk build!

**Comment by flatwhatson** [comment]
Thanks everyone, I'm glad you've found it useful!

**Comment by alphapapa** [comment]
FYI to anyone who needs it, the Emacs 28 branch has been cut, and Guix makes it easy to use with this definition:
```
guix install emacs-native-comp --with-branch=emacs-native-comp=emacs-28
```
