### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by akirakyle** [flatwhatson/guix-channel#16]
I was wondering if you had any plans to upstream this work into guix, especially since now both native comp and pgtk are on emacs master?

**Comment by podiki** [comment]
I'm also curious, and am available to help to submit patches. Doesn't seem like it is much, mostly libgccjit and new variation of the existing guix emacs packages? There is already emacs-next-pgtk that is also on 28.

Edit: For reference, this was brought up on the Guix side back in December 2020: https://issues.guix.gnu.org/44775 But now with emacs-28 and a pgtk version in Guix, maybe we just need the newer libgccjit version and some minor tweaks? Happy to help out.

**Comment by podiki** [comment]
Hi @flatwhatson, anything we can do to help get this in upstream Guix? Seems like a good addition there.

**Comment by podiki** [comment]
With emacs 28.1 officially out, maybe now would be a good time to merge this to Guix? What is needed? There's a WIP 28.1 emacs patch here: https://issues.guix.gnu.org/54829 And thanks again for this channel @flatwhatson

**Comment by podiki** [comment]
native-comp is in upstream guix as of https://git.savannah.gnu.org/cgit/guix.git/commit/?id=dbcba75c0e96d8eb2b0bf9dbb3a49d15b38f80d2 Thanks to the original work of @flatwhatson and then Liliana over on Guix.

I think pgtk is only in the upstream emacs-next-pgtk package.

**Comment by daviwil** [comment]
That is fantastic news, thanks for the update!
