### ISSUE TITLE
What is the checksum calculated over?

### ISSUE THREAD

**Issue by pcn** [flatwhatson/guix-channel#17]
I'm wondering what the checksum is calculated over in https://github.com/flatwhatson/guix-channel/blob/master/flat/packages/emacs.scm#L118-L126? I was thinking of providing a PR to update to the 28.0.92, but I'm not sure how guix calculates that value for a git checkout.

**Comment by emixa-d** [comment]
Presumably it's calculated over a git checkout (with `guix hash -rx`). The lines you referred to contain the used repository and commit in the repository.

**Comment by pcn** [comment]
Thanks! I didn't know what I was searching for.
