### ISSUE TITLE
guix reconfigure fails on emacs-minimal-28.1.drv

### ISSUE THREAD

**Issue by WorldsEndless** [flatwhatson/guix-channel#18]
> builder for \`/gnu/store/5xshrfr600hcyzmdbjn5z2cxw6w3pvfl-emacs-minimal-28.1.drv' failed with exit code 1 build of /gnu/store/5xshrfr600hcyzmdbjn5z2cxw6w3pvfl-emacs-minimal-28.1.drv failed

where the single line in the noted log file is: `/gnu/store/qbmbrw1nd8rbv0gzg7brczmks62d4h51-emacs-minimal-28.1-builder:1:2852: Unknown # object: "#<"`

I'm not sure of the best place to report this issue, but if this isn't it, maybe someone knows where it should be. In any case, I am unable to complete my reconfigure.

**Comment by hugonobrega** [comment]
Here is the culprit/possible fix https://issues.guix.gnu.org/issue/55419

**Comment by flatwhatson** [comment]
Thanks, this should now be fixed
