### ISSUE TITLE
`emacs-pgtk-native-comp` currently doesn't build

### ISSUE THREAD

**Issue by liate7** [flatwhatson/guix-channel#22]
Upstream added a patch to fix super behavior to `emacs-next-pgtk`, but `emacs-pgtk-native-comp` already has a fix for it.  This makes the build fail.

Failing build log attached:
[ldw15d6jzv2b0mnlv58mfwkbxb5lq2-emacs-pgtk-native-comp-28.1.91-checkout.drv.txt](https://github.com/flatwhatson/guix-channel/files/9612675/ldw15d6jzv2b0mnlv58mfwkbxb5lq2-emacs-pgtk-native-comp-28.1.91-checkout.drv.txt)

**Comment by flatwhatson** [comment]
Hi, sorry for the late response, this should now be fixed.

**Comment by liate7** [comment]
Thanks!
