### ISSUE TITLE
User native compilation not working on Guix System

### ISSUE THREAD

**Issue by formbi-kupiec** [flatwhatson/guix-channel#3]
On Arch, this gccemacs package works like a charm. But on Guix System, I get this:
`Warning (comp): x86_64-unknown-linux-gnu-gcc-10.2.0: fatal error: cannot execute 'as': execvp: No such file or directory
`
I guess it has something to do with PATH, because that error doesn't appear when I run gccemacs in an environment with binutils.

**Comment by lafrenierejm** [comment]
I'm getting the same error.

**Comment by flatwhatson** [comment]
Thanks for the report!

A simple solution might be to add binutils as a propagated input, but that would unnecessarily pollute the profile. Perhaps it will be possible to inject the correct path using the driver options

This should be reproducible outside of Guix System by installing into a pure environment. I'll investigate further this evening.

**Comment by flatwhatson** [comment]
I was able to reproduce this error on an ArchLinux system running the following:
```guix environment --pure --ad-hoc emacs-pgtk-native-comp -- emacs --batch --eval '(native-compile "/path/to/some.el")'```

Adding binutils to the driver options resolved the problem for me, I've pushed a fix.

@Chaformbintrano @lafrenierejm please confirm that it works for you on Guix System.
