### ISSUE TITLE
emacs-ignore-empty-xim-styles.patch fails to apply

### ISSUE THREAD

**Issue by MorganJamesSmith** [flatwhatson/guix-channel#4]
emacs-ignore-empty-xim-styles.patch fails to apply

I assume you haven't noticed since emacs-pgtk-native-comp doesn't use this patch, but emacs-native-comp is now failing due to this patch. The patch has a comment saying: "Fix contributed upstream here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=42694." and we are building from the latest git so I don't think the patch is needed anymore anyways.

Thanks for all the good work!!

**Comment by flatwhatson** [comment]
Thanks for the report!  Sorry, you're right, I hadn't been checking compilation of `emacs-native-comp` closely enough.  I've fixed the build to skip that patch, fixed another unrelated compilation error, and now the build is succeeding.  I'll keep a closer eye on it in future.  Cheers!
