### ISSUE TITLE
emacs-pgtk-native-comp - (void-function macroexp-file-name)

### ISSUE THREAD

**Issue by arkhan** [flatwhatson/guix-channel#6]
Greetings, with the last update of flymake it makes use of the new implementation of **macroexp-file-name** and this is not in its branch **pgtk-nativecomp** this function is absent, so it generates many warnings 

Thanks a lot

**Comment by flatwhatson** [comment]
The `pgtk-nativecomp` branch tracks the `feature/pgtk` and `feature/native-comp` branches.  If you're waiting on a change from `master`, you'll need to wait until that's been merged by one of those branches.  The `feature/native-comp` normally merges from `master` about once a week.

In the case of flymake, this is shipped with emacs, and the version of flymake in the `pgtk-nativecomp` branch makes no reference to `macroexp-file-name`.  I guess you're using a bleeding-edge version from some other source which is leading to these warnings.  If this is a problem for you, I'd suggest rolling back to an earlier version of flymake until `master` has been merged, or perhaps just using the built-in version.

**Comment by flatwhatson** [comment]
The `feature/native-comp` branch has now merged the relevant changes, which have also been merged to `pgtk-nativecomp`.
