### ISSUE TITLE
Can't build libgccjit-10

### ISSUE THREAD

**Issue by nueidris** [flatwhatson/guix-channel#7]
I suppose it's the same issue from #5 
 
Here is this giant log :p
[log.log](https://github.com/flatwhatson/guix-channel/files/6057211/log.log)

**Comment by flatwhatson** [comment]
For future reference, it can make a big difference to `gzip log.log` before uploading.  It takes that 9.5Mb file down to 633K.

In this case the error is shown fairly clearly near the end of the log: "No space left on device"

This means that you ran out of disk space while building.  The build was occurring in `/tmp/guix-build-libgccjit-10.2.0.drv-0`, which might be mounted on a small ramdisk depending on your system configuration.  See https://wiki.archlinux.org/index.php/Guix#Building_packages_outside_of_/tmp for more info and a workaround.

**Comment by nueidris** [comment]
@flatwhatson thank you for your response, and sorry for the inconvenience.
I've been mounting /tmp on memory, since I have 1.5TiB (what is weird, since I compile GCC stack one in a week :p). I'll try to follow the instructions and reproduce the build.
Thanks, again
