### ISSUE TITLE
problems with starting emacs-native-comp

### ISSUE THREAD

**Issue by lwiechec** [flatwhatson/guix-channel#9]
Hi, thanks for the publication of the guix channel!

I have more of a question, rather than 'issue':

I added it and built the`emacs-native-comp`:

```
/gnu/store/5kbbgqamh7h6bxldpnh50pzclj24djk0-emacs-native-comp-28.0.50-161.c622627
```

However, when I start, I do see this:

```
> /gnu/store/5kbbgqamh7h6bxldpnh50pzclj24djk0-emacs-native-comp-28.0.50-161.c622627/bin/emacs-28.0.50 
Unknown specializer byte-to-native-func-def
```

what could be the problem here?...

any help appreciated...

**Comment by lurdan** [comment]
I see same error.
In my case, after removing normal emacs (27.2), I can start emacs-native-comp (28.0.50). Maybe something conflicts?

**Comment by flatwhatson** [comment]
Yes, having multiple emacs packages installed in the same guix profile doesn't work well as they both populate `EMACSLOADPATH`.  Unfortunately there doesn't seem to be any mechanism to declare guix packages as conflicting with each other.

**Comment by lwiechec** [comment]
@flatwhatson thanks for the clarification - I thought that I am doing something wrong!

Does it mean that you have switched to use the native comp branch exclusively? how does it fare?

**Comment by flatwhatson** [comment]
Well, you can use separate profiles to run different versions of emacs, they just can't live together in the *same* profile.

I've been using native-comp builds of emacs for over a year, I think it's excellent.  It's quite stable these days, so if you're interested in improved emacs performance I definitely recommend trying it.

**Comment by lwiechec** [comment]
excellent, will give it a go! installing / building now - in 45 mins should be done :)

**Comment by techapu** [comment]
> Yes, having multiple emacs packages installed in the same guix profile doesn't work well as they both populate `EMACSLOADPATH`. Unfortunately there doesn't seem to be any mechanism to declare guix packages as conflicting with each other.

- How can I remove the previous version in a clean way? 
- How can I delete the previous emacs-27.1 path in my environment variable path? I can't figure out where is it saved, my ~/.bashrc doesn't have any info about that.

Thanks!

**Comment by daviwil** [comment]
Do you have it installed in your system configuration?  I just realized that this may be why I'm having the same issue.

**Comment by techapu** [comment]
I didn't thought about that....! Yes, it is in the config scm file... but the question about the location of my path information remains...

**Comment by daviwil** [comment]
That's the solution, then.  The contents of the `EMACSLOADPATH` variable are assembled based on the union of the system profile and any user profiles you've loaded.  If you remove `emacs` from your system profile (or replace it with `emacs-native-comp`) then the 27.2 path will go away.  I verified this on my install a little while ago!

**Comment by spiderbit** [comment]
Hi is there a easy way to replace then emacs as dependency from exwm towards this version of emacs or can you say somehow this version should replace emacs as dependencies for everything?
